import { db } from "./db";
import { cameras, contacts, alerts } from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  const camerasData = [
    {
      name: "Nlongkak Junction Cam 1",
      location: "Rond-point Nlongkak, Yaounde",
      latitude: 3.8667,
      longitude: 11.5167,
      status: "active",
      description: "Main junction camera covering 4-way intersection",
    },
    {
      name: "Mvog-Mbi Market Cam",
      location: "Marche Mvog-Mbi, Yaounde",
      latitude: 3.8583,
      longitude: 11.5083,
      status: "active",
      description: "Market area traffic camera",
    },
    {
      name: "Melen Highway Cam",
      location: "Route de Melen, Yaounde",
      latitude: 3.8750,
      longitude: 11.5250,
      status: "active",
      description: "Highway monitoring camera",
    },
    {
      name: "Central Post Cam",
      location: "Poste Centrale, Yaounde",
      latitude: 3.8650,
      longitude: 11.5200,
      status: "active",
      description: "City center monitoring",
    },
    {
      name: "Bastos Cam 1",
      location: "Quartier Bastos, Yaounde",
      latitude: 3.8800,
      longitude: 11.5100,
      status: "active",
      description: "Residential area camera",
    },
    {
      name: "Akwa Palace Cam",
      location: "Boulevard de la Liberte, Douala",
      latitude: 4.0511,
      longitude: 9.7085,
      status: "active",
      description: "Main boulevard camera near Akwa Palace",
    },
    {
      name: "Bonaberi Bridge Cam",
      location: "Pont du Wouri, Douala",
      latitude: 4.0650,
      longitude: 9.6830,
      status: "active",
      description: "Bridge monitoring camera",
    },
    {
      name: "Deido Junction Cam",
      location: "Carrefour Deido, Douala",
      latitude: 4.0590,
      longitude: 9.7150,
      status: "active",
      description: "Busy junction camera in Deido",
    },
    {
      name: "Ndokotti Roundabout Cam",
      location: "Rond-point Ndokotti, Douala",
      latitude: 4.0420,
      longitude: 9.7350,
      status: "active",
      description: "Major roundabout monitoring",
    },
    {
      name: "Commercial Avenue Cam",
      location: "Commercial Avenue, Bamenda",
      latitude: 5.9597,
      longitude: 10.1460,
      status: "active",
      description: "Main commercial street camera",
    },
    {
      name: "Up Station Cam",
      location: "Up Station, Bamenda",
      latitude: 5.9650,
      longitude: 10.1500,
      status: "active",
      description: "Hilltop area monitoring",
    },
    {
      name: "City Chemist Cam",
      location: "City Chemist Junction, Bamenda",
      latitude: 5.9570,
      longitude: 10.1430,
      status: "active",
      description: "Junction camera near pharmacy",
    },
    {
      name: "Molyko Junction Cam",
      location: "Molyko, Buea",
      latitude: 4.1560,
      longitude: 9.2970,
      status: "active",
      description: "University area junction camera",
    },
    {
      name: "Buea Town Cam",
      location: "Buea Town Center",
      latitude: 4.1570,
      longitude: 9.2410,
      status: "active",
      description: "Town center monitoring camera",
    },
    {
      name: "Mile 17 Cam",
      location: "Mile 17, Buea",
      latitude: 4.1480,
      longitude: 9.3050,
      status: "offline",
      description: "Highway junction camera - under maintenance",
    },
  ];

  await db.insert(cameras).values(camerasData).onConflictDoNothing();
  console.log("Cameras seeded");

  const contactsData = [
    // --- YAOUNDE ---
    {
      name: "SAFEROUTE CM Dispatch",
      role: "dispatcher",
      phone: "+237 677 000 001",
      email: "dispatch@saferoute.cm",
      organization: "SAFEROUTE CM Central Dispatch - Yaounde",
      priority: 1,
      isActive: true,
    },
    {
      name: "Hopital Central de Yaounde",
      role: "hospital",
      phone: "+237 222 231 404",
      email: "urgences@hcy.cm",
      organization: "Hopital Central de Yaounde",
      priority: 1,
      isActive: true,
    },
    {
      name: "CHU de Yaounde",
      role: "hospital",
      phone: "+237 222 231 234",
      email: "urgences@chu-yaounde.cm",
      organization: "Centre Hospitalier Universitaire de Yaounde",
      priority: 1,
      isActive: true,
    },
    {
      name: "Hopital General de Yaounde",
      role: "hospital",
      phone: "+237 222 221 015",
      email: "urgences@hgy.cm",
      organization: "Hopital General de Yaounde",
      priority: 1,
      isActive: true,
    },
    {
      name: "Hopital Militaire de Yaounde",
      role: "hospital",
      phone: "+237 222 230 183",
      email: "urgences@hmy.cm",
      organization: "Hopital Militaire de Region No. 1 - Yaounde",
      priority: 2,
      isActive: true,
    },
    {
      name: "Centre Hospitalier d'Essos",
      role: "hospital",
      phone: "+237 222 231 170",
      email: "contact@chessos.cm",
      organization: "Centre Hospitalier d'Essos (CNPS) - Yaounde",
      priority: 2,
      isActive: true,
    },
    {
      name: "Hopital Gyneco-Obstetrique de Yaounde",
      role: "hospital",
      phone: "+237 222 231 688",
      email: "urgences@hgopy.cm",
      organization: "Hopital Gyneco-Obstetrique et Pediatrique de Yaounde",
      priority: 3,
      isActive: true,
    },
    {
      name: "Commissariat Central Yaounde",
      role: "police",
      phone: "+237 222 234 567",
      email: "contact@police-yaounde.cm",
      organization: "Police Nationale - Yaounde",
      priority: 1,
      isActive: true,
    },
    {
      name: "Gendarmerie Nationale Yaounde",
      role: "police",
      phone: "+237 222 220 761",
      email: "contact@gendarmerie-yaounde.cm",
      organization: "Gendarmerie Nationale - Yaounde",
      priority: 2,
      isActive: true,
    },
    {
      name: "Sapeurs-Pompiers de Yaounde",
      role: "fire",
      phone: "+237 118",
      email: "urgences@pompiers-yaounde.cm",
      organization: "Corps National des Sapeurs-Pompiers - Yaounde",
      priority: 1,
      isActive: true,
    },
    // --- DOUALA ---
    {
      name: "Hopital General de Douala",
      role: "hospital",
      phone: "+237 233 426 020",
      email: "urgences@hgd.cm",
      organization: "Hopital General de Douala",
      priority: 1,
      isActive: true,
    },
    {
      name: "Hopital Laquintinie de Douala",
      role: "hospital",
      phone: "+237 233 424 612",
      email: "urgences@laquintinie.cm",
      organization: "Hopital Laquintinie de Douala",
      priority: 1,
      isActive: true,
    },
    {
      name: "Hopital de District de Bonassama",
      role: "hospital",
      phone: "+237 233 392 145",
      email: "urgences@bonassama.cm",
      organization: "Hopital de District de Bonassama - Douala",
      priority: 2,
      isActive: true,
    },
    {
      name: "Hopital de District de Deido",
      role: "hospital",
      phone: "+237 233 404 218",
      email: "urgences@deido-hospital.cm",
      organization: "Hopital de District de Deido - Douala",
      priority: 2,
      isActive: true,
    },
    {
      name: "Clinique de la Cathedrale Douala",
      role: "hospital",
      phone: "+237 233 431 250",
      email: "contact@clinique-cathedrale.cm",
      organization: "Clinique de la Cathedrale - Douala",
      priority: 3,
      isActive: true,
    },
    {
      name: "Commissariat Central Douala",
      role: "police",
      phone: "+237 233 424 001",
      email: "contact@police-douala.cm",
      organization: "Police Nationale - Douala",
      priority: 1,
      isActive: true,
    },
    {
      name: "Sapeurs-Pompiers de Douala",
      role: "fire",
      phone: "+237 118",
      email: "urgences@pompiers-douala.cm",
      organization: "Corps National des Sapeurs-Pompiers - Douala",
      priority: 1,
      isActive: true,
    },
    // --- BAMENDA ---
    {
      name: "Bamenda Regional Hospital",
      role: "hospital",
      phone: "+237 233 361 122",
      email: "urgences@bamenda-regional.cm",
      organization: "Bamenda Regional Hospital",
      priority: 1,
      isActive: true,
    },
    {
      name: "Mezam Polyclinic Bamenda",
      role: "hospital",
      phone: "+237 233 362 200",
      email: "contact@mezam-polyclinic.cm",
      organization: "Mezam Polyclinic - Bamenda",
      priority: 2,
      isActive: true,
    },
    {
      name: "Mbingo Baptist Hospital",
      role: "hospital",
      phone: "+237 233 311 560",
      email: "urgences@mbingo-baptist.cm",
      organization: "Mbingo Baptist Hospital - Bamenda",
      priority: 2,
      isActive: true,
    },
    {
      name: "Commissariat Central Bamenda",
      role: "police",
      phone: "+237 233 361 017",
      email: "contact@police-bamenda.cm",
      organization: "Police Nationale - Bamenda",
      priority: 1,
      isActive: true,
    },
    {
      name: "Sapeurs-Pompiers de Bamenda",
      role: "fire",
      phone: "+237 118",
      email: "urgences@pompiers-bamenda.cm",
      organization: "Corps National des Sapeurs-Pompiers - Bamenda",
      priority: 1,
      isActive: true,
    },
    // --- BUEA ---
    {
      name: "Buea Regional Hospital",
      role: "hospital",
      phone: "+237 233 322 215",
      email: "urgences@buea-regional.cm",
      organization: "Buea Regional Hospital",
      priority: 1,
      isActive: true,
    },
    {
      name: "Mount Mary Hospital Buea",
      role: "hospital",
      phone: "+237 233 322 487",
      email: "contact@mountmary.cm",
      organization: "Mount Mary Hospital - Buea",
      priority: 2,
      isActive: true,
    },
    {
      name: "Solidarity Clinic Molyko",
      role: "hospital",
      phone: "+237 233 322 310",
      email: "contact@solidarity-clinic.cm",
      organization: "Solidarity Clinic - Molyko, Buea",
      priority: 3,
      isActive: true,
    },
    {
      name: "Commissariat Central Buea",
      role: "police",
      phone: "+237 233 322 002",
      email: "contact@police-buea.cm",
      organization: "Police Nationale - Buea",
      priority: 1,
      isActive: true,
    },
    {
      name: "Sapeurs-Pompiers de Buea",
      role: "fire",
      phone: "+237 118",
      email: "urgences@pompiers-buea.cm",
      organization: "Corps National des Sapeurs-Pompiers - Buea",
      priority: 1,
      isActive: true,
    },
  ];

  await db.insert(contacts).values(contactsData).onConflictDoNothing();
  console.log("Contacts seeded");

  const alertsData = [
    {
      cameraId: 1,
      type: "collision",
      severity: "high",
      confidence: 0.94,
      latitude: 3.8667,
      longitude: 11.5167,
      location: "Rond-point Nlongkak, Yaounde",
      description: "Two-vehicle collision detected at intersection by YOLOv8 AI. Confidence: 94.0%",
      status: "resolved",
      smsSent: true,
      emailSent: true,
      callMade: true,
    },
    {
      cameraId: 2,
      type: "motorcycle",
      severity: "medium",
      confidence: 0.87,
      latitude: 3.8583,
      longitude: 11.5083,
      location: "Marche Mvog-Mbi, Yaounde",
      description: "Motorcycle accident near market entrance detected by AI. Confidence: 87.0%",
      status: "acknowledged",
      smsSent: true,
      emailSent: true,
      callMade: false,
    },
    {
      cameraId: 3,
      type: "pedestrian",
      severity: "high",
      confidence: 0.91,
      latitude: 3.8750,
      longitude: 11.5250,
      location: "Route de Melen, Yaounde",
      description: "Pedestrian incident on highway crossing detected by YOLOv8. Confidence: 91.0%",
      status: "pending",
      smsSent: false,
      emailSent: false,
      callMade: false,
    },
    {
      cameraId: 6,
      type: "multi-vehicle",
      severity: "high",
      confidence: 0.96,
      latitude: 4.0511,
      longitude: 9.7085,
      location: "Boulevard de la Liberte, Douala",
      description: "Multi-vehicle pileup on boulevard detected by AI system. Confidence: 96.0%",
      status: "resolved",
      smsSent: true,
      emailSent: true,
      callMade: true,
    },
    {
      cameraId: 10,
      type: "bicycle",
      severity: "low",
      confidence: 0.83,
      latitude: 5.9597,
      longitude: 10.1460,
      location: "Commercial Avenue, Bamenda",
      description: "Bicycle accident on commercial street detected by AI. Confidence: 83.0%",
      status: "resolved",
      smsSent: true,
      emailSent: false,
      callMade: false,
    },
  ];

  await db.insert(alerts).values(alertsData).onConflictDoNothing();
  console.log("Alerts seeded");

  console.log("Database seeding complete!");
}

seed().catch(console.error);
